/*
 * Copyright 2019-2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.theicenet.cryptography.randomise;

/**
 * A RandomiseService instance is a component which generates <b>secure random</b> data.
 *
 * @apiNote Any implementation of this interface <b>must</b> be <b>unconditionally thread-safe</b>.
 *
 * @author Juan Fidalgo
 * @since 1.0.0
 */
public interface RandomiseService {

  /**
   * Generates a <b>secure random</b> array of bytes with length <b>lengthInBytes</b>.
   *
   * @apiNote Data must be <b>secure random</b> generated.
   *
   * @param lengthInBytes length of the <b>secure random</b> generated byte array
   * @return <b>secure random</b> byte array with length <b>lengthInBytes</b>
   */
  byte[] generateRandom(int lengthInBytes);
}
