image: maven:3.8.2-openjdk-17

pipelines:
  pull-requests:
    '**':
      - step:
          name: Build PR
          caches:
            - maven
          script:
            - rm -f /dev/random
            - ln -s /dev/urandom /dev/random
            - mvn -V -B clean verify
  branches:
    1.2.x:
      - step:
          name: Build master
          caches:
            - maven
          script:
            - rm -f /dev/random
            - ln -s /dev/urandom /dev/random
            - mvn -V -B clean verify
    master:
      - step:
          name: Build master
          caches:
            - maven
          script:
            - rm -f /dev/random
            - ln -s /dev/urandom /dev/random
            - mvn -V -B clean verify

  custom:
    release-to-maven-central:
      - step:
          name: Release to Maven Central
          deployment: maven-central
          caches:
            - maven
          script:
            - rm -f /dev/random
            - ln -s /dev/urandom /dev/random
            - openssl aes-256-cbc -d -a -md sha512 -pbkdf2 -iter 1048576 -pass pass:"$THEICENET_PIPELINE_AES_PASSWORD" -in private-key.gpg.enc -out private-key.gpg
            - gpg --batch --import private-key.gpg
            - git config user.name "TheIceNet Pipeline"
            - git config user.email "pipeline@theicenet.com"
            - mvn -V -B release:clean -Prelease
            - mvn -V -B release:prepare -Prelease
            - mvn -V -B -s settings.xml release:perform -Prelease

