image: maven:3.6.3-jdk-11

pipelines:
  pull-requests:
    '**':
      - step:
          name: Build PR
          caches:
            - maven
          script:
            - mvn -V -B clean verify
  branches:
    master:
      - step:
          name: Build master
          caches:
            - maven
          script:
            - mvn -V -B clean verify
  custom:
    release-to-maven-central:
      - step:
          name: Release to Maven Central
          deployment: maven-central
          caches:
            - maven
          script:
            - openssl aes-256-cbc -d -a -md sha512 -pbkdf2 -iter 1048576 -pass pass:"$THEICENET_RELEASE_PIPELINE_AES_PASSWORD" -in private-key.gpg.enc -out private-key.gpg
            - gpg --batch --import private-key.gpg
            - mvn -V -B release:clean -Prelease
            - mvn -V -B release:prepare -Prelease
            - mvn -V -B -s settings.xml release:perform -Prelease

