cryptography:
  aes:
    key:
      lengthInBits: 256
    initializationVector:
      lengthInBytes: 16
    blockCipher:
      modeOfOperation: CTR
  rsa:
    key:
      lengthInBits: 4096
  keyDerivationFunction:
    pbkdF2WithHmacSHA:
      shaAlgorithm: SHA512
      iterations: 131070
    scrypt:
      cpuMemoryCost: 1048576
      blockSize: 8
      parallelization: 1
    argon2:
      type: ARGON2_ID
      version: ARGON2_VERSION_13
      iterations: 3
      memoryPowOfTwo: 27
      parallelism: 4

