cryptography:
  aes:
    key:
      lengthInBits: 256
    initializationVector:
      lengthInBytes: 16
    blockCipher:
      modeOfOperation: CTR
  rsa:
    key:
      lengthInBits: 4096
  keyDerivationFunction:
    pbkdF2WithHmacSHA:
      shaAlgorithm: SHA512
      iterations: 131070
    scrypt:
      cpuMemoryCost: 1048576
      blockSize: 8
      parallelization: 1

